#ifndef _STASH_PANEL_H_
#define _STASH_PANEL_H_

#include "stdafx.h"
#include "BaseLayout/BaseLayout.h"

namespace Game
{
	class InventorySlot;
	class InventorySize;
}

	ATTRIBUTE_CLASS_LAYOUT(StashPanel, "StashPanel.layout");
	class StashPanel :
		public wraps::BaseLayout
	{
	public:
		StashPanel(MyGUI::Widget* _parent = nullptr);
		virtual ~StashPanel();

		MyGUI::Widget* getMainWidget()
		{
			return this->mMainWidget;
		}

		MyGUI::Widget* StashPanel::getWidgetSlotByScreenPosition(const MyGUI::types::TPoint<int>&  _value);
		MyGUI::Widget* StashPanel::getWidgetSlotByScreenPosition_modified(const MyGUI::types::TPoint<int>&  _value);
		MyGUI::Widget* StashPanel::getWidgetSlotByRC(int r, int c);
		Game::InventorySlot StashPanel::getSlotByWidgetName(std::string name);

		void StashPanel::setAllSlotsColor(MyGUI::Colour color);
		void StashPanel::setHoverSlotsColor(Game::InventorySlot* _slot, Game::InventorySize* _size , MyGUI::Colour color);
		void StashPanel::setHoverSlotsColor(const MyGUI::types::TRect<int>&  _value , MyGUI::Colour color);

		void StashPanel::mclose_eventMouseButtonClick(MyGUI::WidgetPtr _sender);



	private:
	//%LE Widget_Declaration list start
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mRootWidget, "Root");
		MyGUI::Widget* mRootWidget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mslot_container_panelWidget, "slot_container_panel");
		MyGUI::Widget* mslot_container_panelWidget;

		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x0Widget, "stash_slot_0x0");
		MyGUI::Widget* mstash_slot_0x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x1Widget, "stash_slot_0x1");
		MyGUI::Widget* mstash_slot_0x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x2Widget, "stash_slot_0x2");
		MyGUI::Widget* mstash_slot_0x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x3Widget, "stash_slot_0x3");
		MyGUI::Widget* mstash_slot_0x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x4Widget, "stash_slot_0x4");
		MyGUI::Widget* mstash_slot_0x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x5Widget, "stash_slot_0x5");
		MyGUI::Widget* mstash_slot_0x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x6Widget, "stash_slot_0x6");
		MyGUI::Widget* mstash_slot_0x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x7Widget, "stash_slot_0x7");
		MyGUI::Widget* mstash_slot_0x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x8Widget, "stash_slot_0x8");
		MyGUI::Widget* mstash_slot_0x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x9Widget, "stash_slot_0x9");
		MyGUI::Widget* mstash_slot_0x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_0x10Widget, "stash_slot_0x10");
		MyGUI::Widget* mstash_slot_0x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x0Widget, "stash_slot_1x0");
		MyGUI::Widget* mstash_slot_1x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x1Widget, "stash_slot_1x1");
		MyGUI::Widget* mstash_slot_1x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x2Widget, "stash_slot_1x2");
		MyGUI::Widget* mstash_slot_1x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x3Widget, "stash_slot_1x3");
		MyGUI::Widget* mstash_slot_1x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x4Widget, "stash_slot_1x4");
		MyGUI::Widget* mstash_slot_1x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x5Widget, "stash_slot_1x5");
		MyGUI::Widget* mstash_slot_1x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x6Widget, "stash_slot_1x6");
		MyGUI::Widget* mstash_slot_1x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x7Widget, "stash_slot_1x7");
		MyGUI::Widget* mstash_slot_1x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x8Widget, "stash_slot_1x8");
		MyGUI::Widget* mstash_slot_1x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x9Widget, "stash_slot_1x9");
		MyGUI::Widget* mstash_slot_1x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_1x10Widget, "stash_slot_1x10");
		MyGUI::Widget* mstash_slot_1x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x0Widget, "stash_slot_2x0");
		MyGUI::Widget* mstash_slot_2x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x1Widget, "stash_slot_2x1");
		MyGUI::Widget* mstash_slot_2x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x2Widget, "stash_slot_2x2");
		MyGUI::Widget* mstash_slot_2x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x3Widget, "stash_slot_2x3");
		MyGUI::Widget* mstash_slot_2x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x4Widget, "stash_slot_2x4");
		MyGUI::Widget* mstash_slot_2x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x5Widget, "stash_slot_2x5");
		MyGUI::Widget* mstash_slot_2x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x6Widget, "stash_slot_2x6");
		MyGUI::Widget* mstash_slot_2x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x7Widget, "stash_slot_2x7");
		MyGUI::Widget* mstash_slot_2x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x8Widget, "stash_slot_2x8");
		MyGUI::Widget* mstash_slot_2x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x9Widget, "stash_slot_2x9");
		MyGUI::Widget* mstash_slot_2x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_2x10Widget, "stash_slot_2x10");
		MyGUI::Widget* mstash_slot_2x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x0Widget, "stash_slot_3x0");
		MyGUI::Widget* mstash_slot_3x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x1Widget, "stash_slot_3x1");
		MyGUI::Widget* mstash_slot_3x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x2Widget, "stash_slot_3x2");
		MyGUI::Widget* mstash_slot_3x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x3Widget, "stash_slot_3x3");
		MyGUI::Widget* mstash_slot_3x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x4Widget, "stash_slot_3x4");
		MyGUI::Widget* mstash_slot_3x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x5Widget, "stash_slot_3x5");
		MyGUI::Widget* mstash_slot_3x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x6Widget, "stash_slot_3x6");
		MyGUI::Widget* mstash_slot_3x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x7Widget, "stash_slot_3x7");
		MyGUI::Widget* mstash_slot_3x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x8Widget, "stash_slot_3x8");
		MyGUI::Widget* mstash_slot_3x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x9Widget, "stash_slot_3x9");
		MyGUI::Widget* mstash_slot_3x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_3x10Widget, "stash_slot_3x10");
		MyGUI::Widget* mstash_slot_3x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x0Widget, "stash_slot_4x0");
		MyGUI::Widget* mstash_slot_4x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x1Widget, "stash_slot_4x1");
		MyGUI::Widget* mstash_slot_4x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x2Widget, "stash_slot_4x2");
		MyGUI::Widget* mstash_slot_4x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x3Widget, "stash_slot_4x3");
		MyGUI::Widget* mstash_slot_4x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x4Widget, "stash_slot_4x4");
		MyGUI::Widget* mstash_slot_4x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x5Widget, "stash_slot_4x5");
		MyGUI::Widget* mstash_slot_4x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x6Widget, "stash_slot_4x6");
		MyGUI::Widget* mstash_slot_4x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x7Widget, "stash_slot_4x7");
		MyGUI::Widget* mstash_slot_4x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x8Widget, "stash_slot_4x8");
		MyGUI::Widget* mstash_slot_4x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x9Widget, "stash_slot_4x9");
		MyGUI::Widget* mstash_slot_4x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_4x10Widget, "stash_slot_4x10");
		MyGUI::Widget* mstash_slot_4x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x0Widget, "stash_slot_5x0");
		MyGUI::Widget* mstash_slot_5x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x1Widget, "stash_slot_5x1");
		MyGUI::Widget* mstash_slot_5x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x2Widget, "stash_slot_5x2");
		MyGUI::Widget* mstash_slot_5x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x3Widget, "stash_slot_5x3");
		MyGUI::Widget* mstash_slot_5x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x4Widget, "stash_slot_5x4");
		MyGUI::Widget* mstash_slot_5x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x5Widget, "stash_slot_5x5");
		MyGUI::Widget* mstash_slot_5x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x6Widget, "stash_slot_5x6");
		MyGUI::Widget* mstash_slot_5x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x7Widget, "stash_slot_5x7");
		MyGUI::Widget* mstash_slot_5x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x8Widget, "stash_slot_5x8");
		MyGUI::Widget* mstash_slot_5x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x9Widget, "stash_slot_5x9");
		MyGUI::Widget* mstash_slot_5x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_5x10Widget, "stash_slot_5x10");
		MyGUI::Widget* mstash_slot_5x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x0Widget, "stash_slot_6x0");
		MyGUI::Widget* mstash_slot_6x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x1Widget, "stash_slot_6x1");
		MyGUI::Widget* mstash_slot_6x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x2Widget, "stash_slot_6x2");
		MyGUI::Widget* mstash_slot_6x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x3Widget, "stash_slot_6x3");
		MyGUI::Widget* mstash_slot_6x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x4Widget, "stash_slot_6x4");
		MyGUI::Widget* mstash_slot_6x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x5Widget, "stash_slot_6x5");
		MyGUI::Widget* mstash_slot_6x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x6Widget, "stash_slot_6x6");
		MyGUI::Widget* mstash_slot_6x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x7Widget, "stash_slot_6x7");
		MyGUI::Widget* mstash_slot_6x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x8Widget, "stash_slot_6x8");
		MyGUI::Widget* mstash_slot_6x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x9Widget, "stash_slot_6x9");
		MyGUI::Widget* mstash_slot_6x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_6x10Widget, "stash_slot_6x10");
		MyGUI::Widget* mstash_slot_6x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x0Widget, "stash_slot_7x0");
		MyGUI::Widget* mstash_slot_7x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x1Widget, "stash_slot_7x1");
		MyGUI::Widget* mstash_slot_7x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x2Widget, "stash_slot_7x2");
		MyGUI::Widget* mstash_slot_7x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x3Widget, "stash_slot_7x3");
		MyGUI::Widget* mstash_slot_7x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x4Widget, "stash_slot_7x4");
		MyGUI::Widget* mstash_slot_7x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x5Widget, "stash_slot_7x5");
		MyGUI::Widget* mstash_slot_7x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x6Widget, "stash_slot_7x6");
		MyGUI::Widget* mstash_slot_7x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x7Widget, "stash_slot_7x7");
		MyGUI::Widget* mstash_slot_7x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x8Widget, "stash_slot_7x8");
		MyGUI::Widget* mstash_slot_7x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x9Widget, "stash_slot_7x9");
		MyGUI::Widget* mstash_slot_7x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_7x10Widget, "stash_slot_7x10");
		MyGUI::Widget* mstash_slot_7x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x0Widget, "stash_slot_8x0");
		MyGUI::Widget* mstash_slot_8x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x1Widget, "stash_slot_8x1");
		MyGUI::Widget* mstash_slot_8x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x2Widget, "stash_slot_8x2");
		MyGUI::Widget* mstash_slot_8x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x3Widget, "stash_slot_8x3");
		MyGUI::Widget* mstash_slot_8x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x4Widget, "stash_slot_8x4");
		MyGUI::Widget* mstash_slot_8x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x5Widget, "stash_slot_8x5");
		MyGUI::Widget* mstash_slot_8x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x6Widget, "stash_slot_8x6");
		MyGUI::Widget* mstash_slot_8x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x7Widget, "stash_slot_8x7");
		MyGUI::Widget* mstash_slot_8x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x8Widget, "stash_slot_8x8");
		MyGUI::Widget* mstash_slot_8x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x9Widget, "stash_slot_8x9");
		MyGUI::Widget* mstash_slot_8x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_8x10Widget, "stash_slot_8x10");
		MyGUI::Widget* mstash_slot_8x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x0Widget, "stash_slot_9x0");
		MyGUI::Widget* mstash_slot_9x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x1Widget, "stash_slot_9x1");
		MyGUI::Widget* mstash_slot_9x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x2Widget, "stash_slot_9x2");
		MyGUI::Widget* mstash_slot_9x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x3Widget, "stash_slot_9x3");
		MyGUI::Widget* mstash_slot_9x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x4Widget, "stash_slot_9x4");
		MyGUI::Widget* mstash_slot_9x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x5Widget, "stash_slot_9x5");
		MyGUI::Widget* mstash_slot_9x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x6Widget, "stash_slot_9x6");
		MyGUI::Widget* mstash_slot_9x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x7Widget, "stash_slot_9x7");
		MyGUI::Widget* mstash_slot_9x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x8Widget, "stash_slot_9x8");
		MyGUI::Widget* mstash_slot_9x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x9Widget, "stash_slot_9x9");
		MyGUI::Widget* mstash_slot_9x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_9x10Widget, "stash_slot_9x10");
		MyGUI::Widget* mstash_slot_9x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x0Widget, "stash_slot_10x0");
		MyGUI::Widget* mstash_slot_10x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x1Widget, "stash_slot_10x1");
		MyGUI::Widget* mstash_slot_10x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x2Widget, "stash_slot_10x2");
		MyGUI::Widget* mstash_slot_10x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x3Widget, "stash_slot_10x3");
		MyGUI::Widget* mstash_slot_10x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x4Widget, "stash_slot_10x4");
		MyGUI::Widget* mstash_slot_10x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x5Widget, "stash_slot_10x5");
		MyGUI::Widget* mstash_slot_10x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x6Widget, "stash_slot_10x6");
		MyGUI::Widget* mstash_slot_10x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x7Widget, "stash_slot_10x7");
		MyGUI::Widget* mstash_slot_10x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x8Widget, "stash_slot_10x8");
		MyGUI::Widget* mstash_slot_10x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x9Widget, "stash_slot_10x9");
		MyGUI::Widget* mstash_slot_10x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_10x10Widget, "stash_slot_10x10");
		MyGUI::Widget* mstash_slot_10x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x0Widget, "stash_slot_11x0");
		MyGUI::Widget* mstash_slot_11x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x1Widget, "stash_slot_11x1");
		MyGUI::Widget* mstash_slot_11x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x2Widget, "stash_slot_11x2");
		MyGUI::Widget* mstash_slot_11x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x3Widget, "stash_slot_11x3");
		MyGUI::Widget* mstash_slot_11x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x4Widget, "stash_slot_11x4");
		MyGUI::Widget* mstash_slot_11x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x5Widget, "stash_slot_11x5");
		MyGUI::Widget* mstash_slot_11x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x6Widget, "stash_slot_11x6");
		MyGUI::Widget* mstash_slot_11x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x7Widget, "stash_slot_11x7");
		MyGUI::Widget* mstash_slot_11x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x8Widget, "stash_slot_11x8");
		MyGUI::Widget* mstash_slot_11x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x9Widget, "stash_slot_11x9");
		MyGUI::Widget* mstash_slot_11x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_11x10Widget, "stash_slot_11x10");
		MyGUI::Widget* mstash_slot_11x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x0Widget, "stash_slot_12x0");
		MyGUI::Widget* mstash_slot_12x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x1Widget, "stash_slot_12x1");
		MyGUI::Widget* mstash_slot_12x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x2Widget, "stash_slot_12x2");
		MyGUI::Widget* mstash_slot_12x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x3Widget, "stash_slot_12x3");
		MyGUI::Widget* mstash_slot_12x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x4Widget, "stash_slot_12x4");
		MyGUI::Widget* mstash_slot_12x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x5Widget, "stash_slot_12x5");
		MyGUI::Widget* mstash_slot_12x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x6Widget, "stash_slot_12x6");
		MyGUI::Widget* mstash_slot_12x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x7Widget, "stash_slot_12x7");
		MyGUI::Widget* mstash_slot_12x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x8Widget, "stash_slot_12x8");
		MyGUI::Widget* mstash_slot_12x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x9Widget, "stash_slot_12x9");
		MyGUI::Widget* mstash_slot_12x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_12x10Widget, "stash_slot_12x10");
		MyGUI::Widget* mstash_slot_12x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x0Widget, "stash_slot_13x0");
		MyGUI::Widget* mstash_slot_13x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x1Widget, "stash_slot_13x1");
		MyGUI::Widget* mstash_slot_13x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x2Widget, "stash_slot_13x2");
		MyGUI::Widget* mstash_slot_13x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x3Widget, "stash_slot_13x3");
		MyGUI::Widget* mstash_slot_13x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x4Widget, "stash_slot_13x4");
		MyGUI::Widget* mstash_slot_13x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x5Widget, "stash_slot_13x5");
		MyGUI::Widget* mstash_slot_13x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x6Widget, "stash_slot_13x6");
		MyGUI::Widget* mstash_slot_13x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x7Widget, "stash_slot_13x7");
		MyGUI::Widget* mstash_slot_13x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x8Widget, "stash_slot_13x8");
		MyGUI::Widget* mstash_slot_13x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x9Widget, "stash_slot_13x9");
		MyGUI::Widget* mstash_slot_13x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_13x10Widget, "stash_slot_13x10");
		MyGUI::Widget* mstash_slot_13x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x0Widget, "stash_slot_14x0");
		MyGUI::Widget* mstash_slot_14x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x1Widget, "stash_slot_14x1");
		MyGUI::Widget* mstash_slot_14x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x2Widget, "stash_slot_14x2");
		MyGUI::Widget* mstash_slot_14x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x3Widget, "stash_slot_14x3");
		MyGUI::Widget* mstash_slot_14x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x4Widget, "stash_slot_14x4");
		MyGUI::Widget* mstash_slot_14x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x5Widget, "stash_slot_14x5");
		MyGUI::Widget* mstash_slot_14x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x6Widget, "stash_slot_14x6");
		MyGUI::Widget* mstash_slot_14x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x7Widget, "stash_slot_14x7");
		MyGUI::Widget* mstash_slot_14x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x8Widget, "stash_slot_14x8");
		MyGUI::Widget* mstash_slot_14x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x9Widget, "stash_slot_14x9");
		MyGUI::Widget* mstash_slot_14x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_14x10Widget, "stash_slot_14x10");
		MyGUI::Widget* mstash_slot_14x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x0Widget, "stash_slot_15x0");
		MyGUI::Widget* mstash_slot_15x0Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x1Widget, "stash_slot_15x1");
		MyGUI::Widget* mstash_slot_15x1Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x2Widget, "stash_slot_15x2");
		MyGUI::Widget* mstash_slot_15x2Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x3Widget, "stash_slot_15x3");
		MyGUI::Widget* mstash_slot_15x3Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x4Widget, "stash_slot_15x4");
		MyGUI::Widget* mstash_slot_15x4Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x5Widget, "stash_slot_15x5");
		MyGUI::Widget* mstash_slot_15x5Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x6Widget, "stash_slot_15x6");
		MyGUI::Widget* mstash_slot_15x6Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x7Widget, "stash_slot_15x7");
		MyGUI::Widget* mstash_slot_15x7Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x8Widget, "stash_slot_15x8");
		MyGUI::Widget* mstash_slot_15x8Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x9Widget, "stash_slot_15x9");
		MyGUI::Widget* mstash_slot_15x9Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mstash_slot_15x10Widget, "stash_slot_15x10");
		MyGUI::Widget* mstash_slot_15x10Widget;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mclose_buttonButton, "close_button");
		MyGUI::Button* mclose_buttonButton;
		ATTRIBUTE_FIELD_WIDGET_NAME(StashPanel, mgold_EditBox, "gold_");
		MyGUI::EditBox* mgold_EditBox;
	//%LE Widget_Declaration list end
	};


#endif // _STASH_PANEL_H_
